require "user.options"
require "user.plugins"

require "user.autocomplete"
require "user.colorscheme"
require "user.gitsigns"
require "user.hop"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
